--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Rinegone/AdvancedSpawners
build-by-default: true
branches:
- main
projects:
  AdvancedSpawners:
    path: ""
    icon: Spawner.png
...
